### ISSUE TITLE
missing error check in udevNotify()

### ISSUE THREAD

**Issue by yuwata** [libcamera-org/libcamera#15] opened 2024-08-04 02:25 UTC
https://github.com/libcamera-org/libcamera/blob/19bbca3c0b376ba0183f5db53472c8c46cd402b5/src/libcamera/device_enumerator_udev.cpp#L334

`udev_monitor_receive_device()` may return `NULL` on error, and applications using libcamera may trigger assertion.

See https://jenkins-systemd.apps.ocp.cloud.ci.centos.org/job/upstream-vagrant-archlinux/16312/artifact/systemd-centos-ci/artifacts_yia07dbo/vagrant-logs.6bn/vagrant-arch-testsuite.on8/coredumpctl_collect_boot_FAIL.log

**Comment by kbingham** [comment] 2024-08-05 21:50
This does seem legitimate.

Moving the issue to libcamera's bug tracker at https://bugs.libcamera.org/show_bug.cgi?id=230. I'll close this, as this repository is not officially monitored by the libcamera maintainers.

**Closed by kbingham** 2024-08-05 21:50 UTC

**Comment by kbingham** [comment] 2024-08-05 22:32
patch submitted to the libcamera devel mailing list
https://patchwork.libcamera.org/patch/20807/

**Comment by yuwata** [comment] 2024-08-05 23:53
@kbingham Thank you!

**Comment by kbingham** [comment] 2024-08-08 20:14
Merged to libcamera at 62760bd2605a83e663b9003244ff42f8946f8955 - so it will be included in the next release. It would be good to hear what errno this prints if you catch it happening.

**Comment by yuwata** [comment] 2024-08-09 03:52
@kbingham
The patch looks good to me. Thank you for the quick fix!

Our CIs monitor coredump (typically during early boot), but do not monitor any error messages. So, unfortunately, the error message cannot be detected.

If we see similar or another coredump with the next release. I will report.

**Comment by kbingham** [comment] 2024-08-09 06:53
Thanks for the feedback. I was weary it would be difficult to get the information, but I'm fairly confident given the original report that at least the fault should be fixed, but it would be good to determine what the cause was. Still I think that's outside of the control of libcamera.
